### ISSUE TITLE
Select2 tags plugin has inconsistent results

### ISSUE THREAD

**Issue by joker-777** [platanus/activeadmin_addons#421]
Initially, the [tags](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_tags.md) are stored as space-separated values but once I add or remove a tag the values are comma-separated.

**Comment by joker-777** [comment]
@acflint Thanks for letting me know. I'm also using a personal fork where I fixed a couple of things.

**Comment by difernandez** [comment]
Hi all, thanks for reporting this. We moved away from select2 in the new v2 beta, can any of you confirm if this is still an issue in this version with slim select?

**Comment by timothyrobb** [comment]
@difernandez I can confirm this is still happening in `v2.0.0-beta.1`.
I just spent the past few hours wrangling in `jsbundling-rails` and loading all the AA assets from `yarn` so I could use v2 to try and fix this issue, but to no luck.
The initial value is space-separated, even when fed a comma-separated string as a value from formtastic.

* note the `ss` in IDs in the screenshot below, using SlimSelect from v2 rather than Select2 from v1
* screenshot shows that the initial value on the selected element is space-separated
* screenshot shows that the select collection on the element below the selected one is given an array of individual tags
<img width="1075" alt="image" src="https://github.com/platanus/activeadmin_addons/assets/1174168/f25119f6-5f1d-4fa4-a64c-c27db86d37db">

**Comment by timothyrobb** [comment]
Related issue: https://github.com/mbleigh/acts-as-taggable-on/issues/620
Debugging results:
```
[8] pry(#<TagsInput>)> input_value
=> ["peanuts free", "sesame free", "soya free", "mustard free"]
[9] pry(#<TagsInput>)> build_hidden_control(prefixed_method, method_to_input_name, input_value)
=> "<input id=\"recipe_allergy_list\" name=\"recipe[allergy_list]\" value=\"peanuts free sesame free soya free mustard free\" autocomplete=\"off\" type=\"hidden\" />"
```
I'd recommend a patch to `TagsInput` that joins `input_value` inside `render_array_tags` if it's an array.
Or a patch to pull `@options[:value]` for the tags input, and then we can join it ourselves if we hit this problem, as the above github issue suggests.
Currently `@options` nor `@input_html_options` are listened to, so we cannot override the value given to the input.


Looks like the current workaround for using ActsAsTaggable with this, is to create a custom getter that calls `.to_s`, alias the setter, and then use that as the method for the input call in the AA form.
For example, given the above AA form setup, change the model to have the below
```
  acts_as_taggable_on :allergies
  
  def allergy_list_s
    allergy_list.to_s # Converts AATO tags array to comma-separated string, others may want to do `.join(',')`
  end
  alias :allergy_list_s= :allergy_list=
```
and the form like so:
```
permit_params ... , :allergy_list_s
...
      f.input :allergy_list_s, 
        label: "Allergies",
        as: :tags, 
        collection: ActsAsTaggableOn::Tag.for_context(:allergies).pluck(:name)
```

**Comment by timothyrobb** [comment]
Thanks for promising to look into it! Glad my debugging could help.
A patch could definitely help out both cases!

For others who experience this issue in the meantime until that patch is out, here's a more generic patch they can copy-paste into their models (they'll still need to tweak their AA forms to use the new attr, though)
```
  # --- Workaround for ActiveAdmin_Addons issue ---
  # See https://github.com/platanus/activeadmin_addons/issues/421#issuecomment-1565396023
  tag_types.each do |tag_type|
    taggable = tag_type.to_s.singularize
    define_method "#{taggable}_list_s" do
      # Converts AATO tags array to comma-separated string; others may want to do `.join(',')`
      self.send("#{taggable}_list").to_s 
    end

    alias_method "#{taggable}_list_s=", "#{taggable}_list="
  end
  # ---
```
